version: "3"
services:
  db:
    image: postgres:16-alpine
    ports:
      - ${DB_PORT_MAPPING}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  rust:
    build:
      context: .
    command: ["sh", "-c", "diesel migration run && ./blog"]
    environment:
      ROCKET_ADDRESS: ${ROCKET_ADDRESS}
      ROCKET_PORT: ${ROCKET_PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${RUST_PORT_MAPPING}
    depends_on:
      db:
        condition: service_healthy
