# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
services:
  php:
    build: .
    ports:
      - ${PHPPORT}
    environment:
      APP_ENV: prod
    volumes:
      - symfony_volume:/var/www/symfony

  nginx:
    image: nginx:latest
    ports: 
      - ${NGINXPORT}
    volumes: 
      - symfony_volume:/var/www/symfony
      - .docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  symfony_volume: