# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
services:
  php:
    build: .
    ports:
      - "9000:9000"
    environment:
      APP_ENV: prod

  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes: 
      - .:/var/www/symfony 
      - .docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php