services:
  server:
    build:
      context: ./server
    ports:
      - "${HOST_PORT_FOR_SERVER}:${CONTAINER_PORT_FOR_SERVER}"
  client:
    build:
      context: ./client
    ports:
      - "${HOST_PORT_FOR_CLIENT}:${CONTAINER_PORT_FOR_CLIENT}"
    depends_on:
      - server
